version: '3.7'

services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      API_DOMAIN: ${API_DOMAIN}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
    volumes:
      - $PWD/caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
      - $PWD/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  caddy_data:
  caddy_config:
  mysql_db:
  redis_data:
