name: Staging Deployment

concurrency: stage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'
  # push:
  #   branches:
  #     - dev

jobs:
  deployment:
    runs-on: [self-hosted, stage]
    environment: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy Caddy configuration
        run: |
          cp -f /opt/deployment-specific-files/Caddyfile $GITHUB_WORKSPACE/caddy
          cp -f /opt/deployment-specific-files/chain.pem $GITHUB_WORKSPACE/caddy/certs
          cp -f /opt/deployment-specific-files/priv.pem $GITHUB_WORKSPACE/caddy/certs

      - name: Build backend & frontend
        run: docker-compose -f docker-compose.local.yml build backend frontend

      - name: Replace docker images
        run: docker-compose -f docker-compose.local.yml up
      
      - name: Deploy